---
- name: Backend Auto Deployment (Local via Ansible)
  hosts: localhost
  become: no  # No sudo needed

  tasks:
    - name: Set Deployment Path
      set_fact:
        deploy_path: "/Users/priyasidhaiyan/Documents/Ironhack/mongoose"

    - name: Install Dependencies
      command: npm install
      args:
        chdir: "{{ deploy_path }}"

    - name: Run Linter
      command: npm run lint
      args:
        chdir: "{{ deploy_path }}"
      failed_when: false # Stop playbook if linting fails

    - name: Run Tests
      command: npm test
      args:
        chdir: "{{ deploy_path }}"
      register: test_result
      failed_when: false

- name: Handle Test Failures
  when: test_result.rc != 0
  block:
    - name: Log Failure Directly in Prometheus Format
      lineinfile:
        path: "/opt/homebrew/prometheus/deployment.prom"
        create: yes
        line: 'ci_deployment_status{job="ansible", status="failure"} 1'


    - name: Restart Backend Server with PM2
      shell: |
        pm2 restart mongoose-server || pm2 start server.js --name mongoose-server --watch
      args:
        chdir: "{{ deploy_path }}"
      register: pm2_result
      ignore_errors: yes  # Prevent failure from stopping execution

    - name: Debug PM2 Restart Output
      debug:
        var: pm2_result
